# Generated by Django 4.1 on 2022-08-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='№')),
                ('order_number', models.PositiveIntegerField(unique=True, verbose_name='заказ №')),
                ('cost_dollar', models.PositiveIntegerField(verbose_name='стоимость,$')),
                ('delivery_date', models.DateField(verbose_name='Дата')),
                ('cost_rubles', models.PositiveIntegerField(verbose_name='стоимость в руб.')),
            ],
        ),
    ]
