# Generated by Django 4.1 on 2022-08-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['number']},
        ),
    ]
